name: mycheck
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        # make depends on poetry

      - name: install
        run: |
          pip install poetry
          make install
      - name: lint
        run: make lint
